#! /bin/bash

# NOTE(UK): This file is to run a set of queries on R*tree and STR-tree AFTER generating a query Workload.
# In case you wish to generate only Query set and display it with gnuplot, then comment loading commands at the last 2 line.

# ---> SET QUERY SET characteristics:
export qs=100
export query_loc_dist=u  # QUERY location distribution: uniform of gaussian, u or g
# AQAR = qx/qy changes from [0.1, 0.3, 0.7, 1, 1.428, 3.33, 10 ]
# QUERY AREA = Example:  Alan = 16e-4  ==> 0.04 * 0.04   
export qx=0.08
export qy=0.08


# CHANGE THE FOLLOWING ONLY IF NEW INDEX İS LOADED !!..
# DO NOT TOUCH FOLLOWING !!! the following MUST MATCH already exist "data" characteristics:  (Indexes should have been loaded before.)

export ds=30000
export data_loc_dist=u    # DATA LOC. dist.
#POINT DATA:
export dx=0
export dy=0
#REGION:
#export dx=0.01
#export dy=0.01
export d_dist=f     # DATA EXTENT dist.

export capacity=92
export fillfactor=0.999
export treeprefix=tree${ds}_${data_loc_dist}_${dx}_${dy}_${d_dist}_${capacity}

. ./run-QueryGen    # sometime, . at the beginning makes all exports global in the current shell.
./run-QueryExecOnTrees
./run-compare-results

