#! /bin/bash


${bindir}/test-rtree-Generator 1 u $qs $query_loc_dist 0.1 0.1 f $qx $qy ${aqar}   > d1   # 1 u .. 0.1 0.1 f is dummy

# generate only queries..
awk '{if ($1 == 2) print $0}' < d1 > ${queryfile}_${aqar}      
rm -rf d1
awk 'BEGIN {}
{print $3," ",$4; print $5," ",$4; print $5," ",$6; }  # may combine the prints in the same line if you wish.
{print $3," ",$6; print $3," ",$4; print ""}
END{}' ${queryfile}_${aqar} > ${pltdir}/pltquery${aqar}











