#! /bin/bash

# NOTE(utku): You can not run this file standalone. This file is called from "run-GenerateQueriesAndExecOnDyn-STR" in which "ds data_loc_dist qs ..." are set (i.e. exported). 

echo Generating queryset  #"Usage: ds data_loc_dist qs query_loc_dist d_dx d_dy d_dist q_dx q_dy q_dist" 

mkdir -p  ~/eclipse-workspace/test-build/query  # -p flag: mk dir only if dir does not exist.
export querydir=~/eclipse-workspace/test-build/query

export qpostfix=${qs}_${query_loc_dist}_${qx}_${qy}
export queryfile=${querydir}/query${qpostfix}

export bindir=~/eclipse-workspace/test-build/
export dbdir=~/eclipse-workspace/test-build/database/${ds}

mkdir -p ~/eclipse-workspace/test-build/plt   # -p flag: mk dir only if dir does not exist.
export pltdir=~/eclipse-workspace/test-build/plt

mkdir -p ~/eclipse-workspace/test-build/results
export resultsdir=~/eclipse-workspace/test-build/results


#time ../../test-rtree-Generator $ds $data_loc_dist $qs $query_loc_dist $dx $dy $d_dist $qx $qy $q_dist > d
# time ../../test-rtree-Generator 1 u $qs $query_loc_dist 0.1 0.1 f $qx $qy $q_dist > d   # 1 u .. 0.1 0.1 f is dummy

export aqar=0.1
./GenQry

export aqar=0.3
./GenQry

export aqar=0.7
./GenQry

export aqar=1
./GenQry

export aqar=1.4
./GenQry

export aqar=3.3
./GenQry

export aqar=10
./GenQry










