#! /bin/bash

# NOTE(utku): You can not run this file standalone. This file is called from "run-GenerateQueriesAndExecOnDyn-STR" in which "ds data_loc_dist qs ..." are set (i.e. exported). 

echo Generating queryset  #"Usage: ds data_loc_dist qs query_loc_dist d_dx d_dy d_dist q_dx q_dy q_dist" 

#time ../../test-rtree-Generator $ds $data_loc_dist $qs $query_loc_dist $dx $dy $d_dist $qx $qy $q_dist > d
# time ../../test-rtree-Generator 1 u $qs $query_loc_dist 0.1 0.1 f $qx $qy $q_dist > d   # 1 u .. 0.1 0.1 f is dummy

export aqar=0.1
bash $SCRIPT_PATH/GenQry

export aqar=0.3
bash $SCRIPT_PATH/GenQry

export aqar=0.7
bash $SCRIPT_PATH/GenQry

export aqar=1
bash $SCRIPT_PATH/GenQry

export aqar=1.4
bash $SCRIPT_PATH/GenQry

export aqar=3.3
bash $SCRIPT_PATH/GenQry

export aqar=10
bash $SCRIPT_PATH/GenQry










