#! /bin/bash

# utku: Query Modes:  [intersection | 10NN | selfjoin | contains]

############## R*-tree: ##########################
export treename=D_${treeprefix}
export timestatsfile=1

for i in 0.1 0.3 0.7 1 1.4 3.3 10; do    
	export aqar="$i";
	bash $SCRIPT_PATH/QryExec;
	done

mv  $timestatsfile $pltdir  

############   STR-tree    ##########################

export treename=S_${treeprefix}_1
export timestatsfile=2

for i in 0.1 0.3 0.7 1 1.4 3.3 10; do    
	export aqar="$i";
	bash $SCRIPT_PATH/QryExec;
	done

mv  $timestatsfile $pltdir  

########   Adp STR-tree  ########################

export timestatsfile=3

for i in 0.1 0.3 0.7 1 1.4 3.3 10; do    
	export aqar="$i";
	export treename=S_${treeprefix}_${aqar};
	bash $SCRIPT_PATH/QryExec;
	done

mv  $timestatsfile $pltdir  

########################################
 


