#! /bin/bash

echo STR Load R-Tree $treename 
time ${bindir}/test-rtree-RTreeBulkLoad $datafile $treename $capacity $fillfactor ${aqar} $pS $bP 2> r 1>${pltdir}/pltSTRLevel0_${aqar}  #redirect cerr to 'r' AND redirect cout to plt...file
awk '{if ($1 ~ /Time/  || 
		  $1 ~ /TOTAL/ || 
		  $1 ~ /Buffer/ || 
		  $1 ~ /Fill/ || 
		  ($1 ~ /Index/ && $2 ~ /capacity/) || 
		  $1 ~ /Utilization/ || 
		  $1 ~ /Buffer/ || 
		  $2 ~ /height/ || 
		  $1 ~ /Number/ || 
		  $1 ~ /Read/|| 
		  $1 ~ /Write/|| 
		  $1 ~ /Level/) print $0}' < r > ${treename}-Loading-Stats
rm -rf r

# mv already replaces..! do not need to remove old file.
mv  ${treename}.dat ${treename}.idx ${treename}-Loading-Stats ${dbdir}/





