#! /bin/bash

# NOTE(utku): You can not run this file standalone. This file is called from "run-GenerateDataAndLoadDyn-STR" in which "ds data_loc_dist qs ..." are set (i.e. exported). 

# utku: You may gplot "datafile" and "queryfile" by "GNUPLOT on pltdata, pltquery"  
# utku: Query Modes:  [intersection | 10NN | selfjoin | contains]

# $datafile, ${ds}, ${data_loc_dist}, ${dx}, ${dy}, ${d_dist}"  has already been set..!

export capacity=92
export fillfactor=0.999

export treeprefix=tree${ds}_${data_loc_dist}_${dx}_${dy}_${d_dist}_${capacity}


# 2>&1 : combines (or called redirect) standard error (stderr) with standard out (stdout)
# > r  : redirect output to file r with replacing r.  >> : redirect and append to file r.
#time ../../test-rtree-RTreeBulkLoad $datafile $Streename $capacity $fillfactor $r $pS $bP > r 2>&1  

# Ordinary STR:
export aqar=1
export treename=S_${treeprefix}_${aqar}    #Bu normal STR tree
bash "$SCRIPT_PATH"/loadStree


# Below are Adaptive STR:
export aqar=0.1
export treename=S_${treeprefix}_${aqar}
bash "$SCRIPT_PATH"/loadStree

export aqar=0.3
export treename=S_${treeprefix}_${aqar}
bash "$SCRIPT_PATH"/loadStree

export aqar=0.7
export treename=S_${treeprefix}_${aqar}
bash "$SCRIPT_PATH"/loadStree



export aqar=1.4
export treename=S_${treeprefix}_${aqar}
bash "$SCRIPT_PATH"/loadStree

export aqar=3.3
export treename=S_${treeprefix}_${aqar}
bash "$SCRIPT_PATH"/loadStree

export aqar=10
export treename=S_${treeprefix}_${aqar}
bash "$SCRIPT_PATH"/loadStree




