#! /bin/bash

# NOTE(utku): You can not run this file standalone. This file is called from "run-GenerateDataAndLoadDyn-STR" in which "ds data_loc_dist qs ..." are set (i.e. exported). 
# ATTENTION: export x = 5  --> degil export x=5 olmalı 

echo Generating dataset  #"Usage: ds data_loc_dist qs query_loc_dist d_dx d_dy d_dist q_dx q_dy q_dist" 

mkdir -p  ~/eclipse-workspace/test-build/data  # -p flag: mk dir only if dir does not exist.
export datadir=~/eclipse-workspace/test-build/data 
export dpostfix=${ds}_${data_loc_dist}_${dx}_${dy}_${d_dist}

export datafile=${datadir}/data${dpostfix}

mkdir -p ~/eclipse-workspace/test-build/plt   # -p flag: mk dir only if dir does not exist.
export pltdir=~/eclipse-workspace/test-build/plt

export bindir=~/eclipse-workspace/test-build/

mkdir -p ~/eclipse-workspace/test-build/database/${ds}    # -p flag: mk dir only if dir does not exist.
export dbdir=~/eclipse-workspace/test-build/database/${ds}

time ${bindir}/test-rtree-Generator $ds $data_loc_dist 0 u $dx $dy $d_dist 0.1 0.1 f > d   # 0 u ... 0.1 0.1 f : dummy values..

awk '{if ($1 != 2) print $0}' < d > ${datafile}   
rm -rf d

# plotting requires 4 edge points of MBR
awk 'BEGIN {}
{print $3," ",$4; print $5," ",$4; print $5," ",$6; }  # may combine the prints in the same line if you wish.
{print $3," ",$6; print $3," ",$4; print ""}
END{}' ${datafile} > ${pltdir}/pltdata

# you may plot data and query with the following command: (Of course never uncomment the following here)
# gnuplot> plot "pltdata" using 1:2 w l, "pltquery" using 1:2 with lines lw 4
